server:
 port: 8081
auth:
  jwt:
    expiration: 1800000
    secret: secret

server:
  port: 8080
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: ssl0.ovh.net
    password: fQR7OSq2xt5Ay53Ms0
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          ssl:
            enable: true
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
    username: info@propertyweb.be
